all:
	pdflatex -output-directory build/ ekf_output_1.tex
	pdflatex -output-directory build/ ekf_output_2.tex
	pdflatex -output-directory build/ ekf_output_3.tex
	cp build/ekf_output_1.pdf .
	cp build/ekf_output_2.pdf .
	cp build/ekf_output_3.pdf .


